/**
 * Copies packages/{name}/docs/ into apps/docs/src/packages/{name}/ for each
 * package in DOCS_PACKAGES. Fails loudly if any Markdown link escapes the
 * source docs/ directory (e.g. ../../src/foo.ts) — those links would silently
 * produce broken pages after the copy.
 *
 * Root-relative VitePress links (starting with /) and external URLs are
 * always allowed.
 */

import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { DOCS_PACKAGES } from './docs-packages.js';

const WORKSPACE_ROOT = resolve(__dirname, '../../..');
const DEST_ROOT = join(WORKSPACE_ROOT, 'apps/docs/src/packages');

// Match Markdown links: [text](target) and ![text](target)
// Captures the link target (group 1).
const MD_LINK_RE = /!?\[(?:[^\]]*)\]\(([^)]+)\)/g;

function checkEscapingLinks(filePath: string, content: string, docsDir: string): void {
  const errors: string[] = [];

  for (const match of content.matchAll(MD_LINK_RE)) {
    const target = match[1]!.split(' ')[0]!; // strip optional title after space

    // Allow absolute VitePress paths, external URLs, anchors, and mailto:
    if (target.startsWith('/') || target.startsWith('http') || target.startsWith('#') || target.startsWith('mailto:')) {
      continue;
    }

    // Resolve the target relative to the file's directory and check it stays
    // within the docs/ directory.
    const fileDir = dirname(filePath);
    const resolved = resolve(fileDir, target);
    const rel = relative(docsDir, resolved);

    if (rel.startsWith('..')) {
      errors.push(`  ${relative(WORKSPACE_ROOT, filePath)}: link "${target}" escapes docs/ directory`);
    }
  }

  if (errors.length > 0) {
    console.error('sync-package-docs: escaping links detected — fix these before committing:\n' + errors.join('\n'));
    process.exit(1);
  }
}

function copyDir(src: string, dest: string, docsDir: string): void {
  mkdirSync(dest, { recursive: true });

  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      copyDir(srcPath, destPath, docsDir);
    } else if (entry.isFile()) {
      if (entry.name.endsWith('.md')) {
        const content = readFileSync(srcPath, 'utf8');
        checkEscapingLinks(srcPath, content, docsDir);
        copyFileSync(srcPath, destPath);
      } else if (/\.(png|jpg|jpeg|gif|svg|webp)$/i.test(entry.name)) {
        copyFileSync(srcPath, destPath);
      }
    }
  }
}

// Clean destination
rmSync(DEST_ROOT, { recursive: true, force: true });

for (const pkg of DOCS_PACKAGES) {
  const srcDocs = join(WORKSPACE_ROOT, 'packages', pkg, 'docs');
  const dest = join(DEST_ROOT, pkg);

  copyDir(srcDocs, dest, srcDocs);

  writeFileSync(
    join(DEST_ROOT, '.generated'),
    'This directory is generated by `nx run docs:generate`. Do not edit files here directly.\n',
  );

  console.log(`synced packages/${pkg}/docs → apps/docs/src/packages/${pkg}`);
}
